import React, { useState } from 'react';
import { useAppStore } from '../../store/useAppStore';
import { copyToClipboard } from '../../utils/cn';
import {
    Copy,
    Check,
    Terminal,
    FileJson,
} from 'lucide-react';

export const ScriptExporterView: React.FC = () => {
    const { packageManager, projectName, setProjectName, addToast } = useAppStore();
    const [activeScriptTab, setActiveScriptTab] = useState<'bash' | 'powershell' | 'package_json'>('bash');
    const [copied, setCopied] = useState(false);

    // Generate Bash script
    const generateBashScript = () => {
        const installCmd =
            packageManager === 'npm'
                ? `npm install\nnpm install tailwindcss @tailwindcss/vite\nnpm install react-router-dom axios zustand @tanstack/react-query react-hook-form zod @hookform/resolvers react-hot-toast lucide-react dayjs clsx tailwind-merge jwt-decode motion\nnpm install -D @types/node eslint prettier eslint-plugin-react-hooks eslint-plugin-react-refresh`
                : packageManager === 'yarn'
                    ? `yarn install\nyarn add tailwindcss @tailwindcss/vite\nyarn add react-router-dom axios zustand @tanstack/react-query react-hook-form zod @hookform/resolvers react-hot-toast lucide-react dayjs clsx tailwind-merge jwt-decode motion\nyarn add -D @types/node eslint prettier eslint-plugin-react-hooks eslint-plugin-react-refresh`
                    : packageManager === 'pnpm'
                        ? `pnpm install\npnpm add tailwindcss @tailwindcss/vite\npnpm add react-router-dom axios zustand @tanstack/react-query react-hook-form zod @hookform/resolvers react-hot-toast lucide-react dayjs clsx tailwind-merge jwt-decode motion\npnpm add -D @types/node eslint prettier eslint-plugin-react-hooks eslint-plugin-react-refresh`
                        : `bun install\nbun add tailwindcss @tailwindcss/vite\nbun add react-router-dom axios zustand @tanstack/react-query react-hook-form zod @hookform/resolvers react-hot-toast lucide-react dayjs clsx tailwind-merge jwt-decode motion\nbun add -d @types/node eslint prettier eslint-plugin-react-hooks eslint-plugin-react-refresh`;

        const createCmd =
            packageManager === 'npm'
                ? `npm create vite@latest ${projectName} -- --template react-ts`
                : packageManager === 'yarn'
                    ? `yarn create vite ${projectName} --template react-ts`
                    : packageManager === 'pnpm'
                        ? `pnpm create vite ${projectName} --template react-ts`
                        : `bun create vite ${projectName} --template react-ts`;

        return `#!/bin/bash
# ==========================================================
# DeepCode Enterprise React + Vite + Tailwind v4 Setup Script
# Auto-generated by DeepCode Architect
# ==========================================================

set -e

echo "🚀 Bắt đầu khởi tạo dự án: ${projectName}..."

# 1. Tạo project Vite
${createCmd}
cd ${projectName}

# 2. Cài đặt các thư viện
echo "📦 Đang cài đặt dependencies và Tailwind v4..."
${installCmd}

# 3. Tạo cấu trúc thư mục Doanh nghiệp
echo "📁 Đang tạo cây thư mục chuẩn..."
mkdir -p src/assets
mkdir -p src/components/common
mkdir -p src/components/layout
mkdir -p src/components/ui
mkdir -p src/features/auth
mkdir -p src/hooks
mkdir -p src/layouts
mkdir -p src/pages
mkdir -p src/routes
mkdir -p src/services/api
mkdir -p src/services/auth
mkdir -p src/store
mkdir -p src/types
mkdir -p src/utils
mkdir -p src/constants
mkdir -p src/styles

# 4. Tạo file cấu hình Vite
echo "⚙️ Đang tạo vite.config.ts..."
cat << 'EOF' > vite.config.ts
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
  ],
})
EOF

# 5. Cấu hình Tailwind CSS v4 trong index.css
echo "🎨 Đang tạo src/index.css..."
echo '@import "tailwindcss";' > src/index.css

# 6. Tạo file App.tsx
echo "📄 Đang tạo src/App.tsx..."
cat << 'EOF' > src/App.tsx
function App() {
  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-100">
      <h1 className="text-5xl font-bold text-orange-500">
        DeepCode React + Vite + TailwindCSS
      </h1>
    </div>
  );
}

export default App;
EOF

echo "✨ Khởi tạo hoàn tất! Chạy các lệnh sau để bắt đầu:"
echo "👉 cd ${projectName}"
echo "👉 ${packageManager === 'npm' ? 'npm run dev' : packageManager + ' dev'}"
`;
    };

    // Generate PowerShell script
    const generatePowershellScript = () => {
        return `# ==========================================================
# DeepCode Enterprise React + Vite + Tailwind v4 PowerShell Script
# Auto-generated for Windows Environment
# ==========================================================

Write-Host "🚀 Đang khởi tạo dự án: ${projectName}..." -ForegroundColor Cyan

# 1. Tạo project Vite
${packageManager === 'npm'
                ? `npm create vite@latest ${projectName} -- --template react-ts`
                : `${packageManager} create vite ${projectName} --template react-ts`
            }
Set-Location ${projectName}

# 2. Cài đặt thư viện
Write-Host "📦 Cài đặt thư viện..." -ForegroundColor Yellow
${packageManager === 'npm'
                ? `npm install
npm install tailwindcss @tailwindcss/vite
npm install react-router-dom axios zustand @tanstack/react-query react-hook-form zod @hookform/resolvers react-hot-toast lucide-react dayjs clsx tailwind-merge jwt-decode motion
npm install -D @types/node eslint prettier eslint-plugin-react-hooks eslint-plugin-react-refresh`
                : packageManager === 'yarn'
                    ? `yarn install
yarn add tailwindcss @tailwindcss/vite
yarn add react-router-dom axios zustand @tanstack/react-query react-hook-form zod @hookform/resolvers react-hot-toast lucide-react dayjs clsx tailwind-merge jwt-decode motion
yarn add -D @types/node eslint prettier eslint-plugin-react-hooks eslint-plugin-react-refresh`
                    : packageManager === 'pnpm'
                        ? `pnpm install
pnpm add tailwindcss @tailwindcss/vite
pnpm add react-router-dom axios zustand @tanstack/react-query react-hook-form zod @hookform/resolvers react-hot-toast lucide-react dayjs clsx tailwind-merge jwt-decode motion
pnpm add -D @types/node eslint prettier eslint-plugin-react-hooks eslint-plugin-react-refresh`
                        : `bun install
bun add tailwindcss @tailwindcss/vite
bun add react-router-dom axios zustand @tanstack/react-query react-hook-form zod @hookform/resolvers react-hot-toast lucide-react dayjs clsx tailwind-merge jwt-decode motion
bun add -d @types/node eslint prettier eslint-plugin-react-hooks eslint-plugin-react-refresh`
            }

# 3. Tạo thư mục
New-Item -ItemType Directory -Force -Path "src/assets","src/components/common","src/components/layout","src/components/ui","src/features/auth","src/hooks","src/layouts","src/pages","src/routes","src/services/api","src/services/auth","src/store","src/types","src/utils","src/constants","src/styles"

# 4. Ghi file index.css
Set-Content -Path "src/index.css" -Value '@import "tailwindcss";'

Write-Host "✅ Hoàn tất thiết lập! Chạy ${packageManager === 'npm' ? 'npm run dev' : packageManager + ' dev'} để khởi động." -ForegroundColor Green
`;
    };

    const generatePackageJson = () => {
        return JSON.stringify(
            {
                name: projectName,
                private: true,
                version: '1.0.0',
                type: 'module',
                scripts: {
                    dev: 'vite',
                    build: 'tsc -b && vite build',
                    preview: 'vite preview',
                    lint: 'eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0',
                },
                dependencies: {
                    '@hookform/resolvers': '^3.10.0',
                    '@tailwindcss/vite': '^4.1.14',
                    '@tanstack/react-query': '^5.66.0',
                    axios: '^1.7.9',
                    clsx: '^2.1.1',
                    dayjs: '^1.11.13',
                    'jwt-decode': '^4.0.0',
                    'lucide-react': '^0.475.0',
                    motion: '^12.0.0',
                    react: '^19.0.0',
                    'react-dom': '^19.0.0',
                    'react-hook-form': '^7.54.2',
                    'react-hot-toast': '^2.5.2',
                    'react-router-dom': '^7.1.5',
                    'tailwind-merge': '^3.0.1',
                    zod: '^3.24.2',
                    zustand: '^5.0.3',
                },
                devDependencies: {
                    '@types/node': '^22.13.0',
                    '@types/react': '^19.0.8',
                    '@types/react-dom': '^19.0.3',
                    '@vitejs/plugin-react': '^5.0.0',
                    eslint: '^9.19.0',
                    'eslint-plugin-react-hooks': '^5.1.0',
                    'eslint-plugin-react-refresh': '^0.4.18',
                    prettier: '^3.4.2',
                    tailwindcss: '^4.1.14',
                    typescript: '~5.8.0',
                    vite: '^6.2.0',
                },
            },
            null,
            2
        );
    };

    const getActiveContent = () => {
        if (activeScriptTab === 'bash') return generateBashScript();
        if (activeScriptTab === 'powershell') return generatePowershellScript();
        return generatePackageJson();
    };

    const handleCopy = async () => {
        const content = getActiveContent();
        const ok = await copyToClipboard(content);
        if (ok) {
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
            addToast({
                type: 'success',
                title: 'Đã copy kịch bản tự động!',
                message: 'Bạn có thể lưu thành file và thực thi trên terminal.',
            });
        }
    };

    return (
        <div className="space-y-6 animate-fadeIn">
            {/* Header */}
            <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-6 flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div>
                    <div className="inline-flex items-center gap-1.5 px-3 py-1 bg-sky-500/10 border border-sky-500/20 text-sky-400 rounded-full text-xs font-semibold mb-2">
                        <Terminal className="w-3.5 h-3.5" />
                        Trình xuất kịch bản tự động hóa (Script Automation)
                    </div>
                    <h2 className="text-xl font-bold text-white">
                        Tạo Toàn bộ Dự án Chỉ Bằng 1 File Script
                    </h2>
                    <p className="text-xs text-slate-400 mt-1">
                        Tải về hoặc sao chép script Bash (.sh) hoặc PowerShell (.ps1) để tự động tạo cây thư mục và cài đặt tất cả packages.
                    </p>
                </div>

                <div className="flex items-center gap-2">
                    <input
                        type="text"
                        value={projectName}
                        onChange={(e) => setProjectName(e.target.value)}
                        placeholder="Tên project..."
                        className="px-3 py-1.5 text-xs bg-slate-950 border border-slate-700 rounded-lg text-orange-400 font-mono focus:outline-none focus:border-orange-500"
                    />
                </div>
            </div>

            {/* Script Tab Navigator */}
            <div className="bg-slate-900/90 border border-slate-800 rounded-2xl overflow-hidden shadow-2xl">
                <div className="bg-slate-950 border-b border-slate-800 px-4 py-2.5 flex items-center justify-between">
                    <div className="flex items-center gap-2">
                        <button
                            onClick={() => setActiveScriptTab('bash')}
                            className={`px-3 py-1.5 text-xs font-semibold rounded-lg transition-colors flex items-center gap-1.5 cursor-pointer ${activeScriptTab === 'bash'
                                    ? 'bg-orange-500 text-white'
                                    : 'text-slate-400 hover:text-white'
                                }`}
                        >
                            <Terminal className="w-3.5 h-3.5" /> setup.sh (Linux / macOS)
                        </button>

                        <button
                            onClick={() => setActiveScriptTab('powershell')}
                            className={`px-3 py-1.5 text-xs font-semibold rounded-lg transition-colors flex items-center gap-1.5 cursor-pointer ${activeScriptTab === 'powershell'
                                    ? 'bg-orange-500 text-white'
                                    : 'text-slate-400 hover:text-white'
                                }`}
                        >
                            <Terminal className="w-3.5 h-3.5" /> setup.ps1 (Windows)
                        </button>

                        <button
                            onClick={() => setActiveScriptTab('package_json')}
                            className={`px-3 py-1.5 text-xs font-semibold rounded-lg transition-colors flex items-center gap-1.5 cursor-pointer ${activeScriptTab === 'package_json'
                                    ? 'bg-orange-500 text-white'
                                    : 'text-slate-400 hover:text-white'
                                }`}
                        >
                            <FileJson className="w-3.5 h-3.5" /> package.json (Đầy đủ)
                        </button>
                    </div>

                    <button
                        onClick={handleCopy}
                        className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold rounded-lg transition-colors active:scale-95 cursor-pointer"
                    >
                        {copied ? (
                            <>
                                <Check className="w-3.5 h-3.5 text-emerald-400" />
                                <span className="text-emerald-400">Đã copy</span>
                            </>
                        ) : (
                            <>
                                <Copy className="w-3.5 h-3.5" />
                                <span>Copy Toàn bộ Script</span>
                            </>
                        )}
                    </button>
                </div>

                {/* Code Content */}
                <div className="p-4 bg-slate-950/70">
                    <pre className="font-mono text-xs text-orange-400/90 leading-relaxed overflow-x-auto p-3 bg-slate-950 border border-slate-900 rounded-xl max-h-[500px]">
                        <code>{getActiveContent()}</code>
                    </pre>
                </div>
            </div>
        </div>
    );
};